//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BCDemo.rc
//
#define IDB_TOOLBAR                     101
#define IDB_PIN                         102
#define IDI_ICON                        103
#define IDI_CLOCK                       104
#define IDR_FRAMEMENU                   105
#define IDR_CHILDMENU                   106
#define IDR_ACCEL                       107
#define IDM_XPSTYLEMENUS                108
#define IDM_XPSYLEMENUS                 108
#define ID_OPTIONS_XPSTYLEMENUS         109
#define IDM_WINDOWS                     110
#define ID_WINDOW_WINDOWS               111
#define IDM_ABOUTBRAINCHILD             112
#define ID_Menu                         114
#define ID_DUMMY_IDM                    115
#define ID_CHANGECASING_A               120
#define ID_CHANGECASING_B               121
#define ID_CHANGECASING_C               122
#define ID_CHANGECASING_D               123
#define ID_CHANGECASING_E               124
#define ID_CHANGECASING_F               125
#define ID_CHANGECASING_G               126
#define ID_CHANGECASING_H               127
#define ID_CHANGECASING_I               128
#define ID_CHANGECASING_J               129
#define ID_CHANGECASING_K               130
#define ID_CHANGECASING_L               131
#define ID_CHANGECASING_M               132
#define ID_CHANGECASING_N               133
#define ID_CHANGECASING_O               134
#define ID_CHANGECASING_P               135
#define ID_CHANGECASING_Q               136
#define ID_CHANGECASING_R               137
#define ID_CHANGECASING_S               138
#define ID_CHANGECASING_T               139
#define ID_CHANGECASING_U               140
#define ID_CHANGECASING_V               141
#define ID_CHANGECASING_W               142
#define ID_CHANGECASING_X               143
#define ID_CHANGECASING_Y               144
#define ID_CHANGECASING_Z               145
#define ID_CHANGECASING_0               146
#define ID_CHANGECASING_1               147
#define ID_CHANGECASING_2               148
#define ID_CHANGECASING_3               149
#define ID_CHANGECASING_4               150
#define ID_CHANGECASING_5               151
#define ID_CHANGECASING_6               152
#define ID_CHANGECASING_7               153
#define ID_CHANGECASING_8               154
#define ID_CHANGECASING_9               155
#define ID_CHANGECASING_A156            156
#define ID_CHANGECASING_B157            157
#define ID_CHANGECASING_C158            158
#define ID_CHANGECASING_D159            159
#define ID_CHANGECASING_E160            160
#define ID_CHANGECASING_F161            161
#define ID_CHANGECASING_G162            162
#define ID_CHANGECASING_H163            163
#define ID_CHANGECASING_I164            164
#define ID_CHANGECASING_J165            165
#define ID_CHANGECASING_K166            166
#define ID_CHANGECASING_L167            167
#define ID_CHANGECASING_M168            168
#define ID_CHANGECASING_N169            169
#define ID_CHANGECASING_O170            170
#define ID_CHANGECASING_P171            171
#define ID_CHANGECASING_Q172            172
#define ID_CHANGECASING_R173            173
#define ID_CHANGECASING_S174            174
#define ID_CHANGECASING_T175            175
#define ID_CHANGECASING_U176            176
#define ID_CHANGECASING_V177            177
#define ID_CHANGECASING_W178            178
#define ID_CHANGECASING_X179            179
#define ID_CHANGECASING_Y180            180
#define ID_CHANGECASING_Z181            181
#define IDM_NEW                         40001
#define IDM_OPEN                        40002
#define IDM_HOTFILES                    40004
#define IDM_EXIT                        40005
#define IDM_NEWWINDOW                   40007
#define IDM_CONFIG                      40008
#define IDM_NEWONSTART                  40009
#define IDM_FANCYMENU                   40010
#define IDM_ABOUT                       40011
#define IDM_CLOSE                       40012
#define IDM_CLOSEALL                    40013
#define IDM_SAVE                        40014
#define IDM_SAVEAS                      40016
#define IDM_SAVEALL                     40017
#define IDM_READONLY                    40018
#define IDM_PROPERTIES                  40019
#define IDM_PRINT                       40020
#define IDM_RECENTFILES                 40021
#define IDM_ADDTOHOT                    40022
#define IDM_UNDO                        40023
#define IDM_REDO                        40024
#define IDM_CUT                         40025
#define IDM_COPY                        40026
#define IDM_PASTE                       40027
#define IDM_DELETE                      40028
#define IDM_SELECTALL                   40029
#define IDM_INVERTCASE                  40030
#define IDM_UPPERCASE                   40031
#define IDM_LOWERCASE                   40032
#define IDM_FIND                        40033
#define IDM_FINDNEXT                    40034
#define IDM_FINDPREV                    40035
#define IDM_REPLACE                     40036
#define IDM_GOTO                        40037
#define IDM_TOGGLEBM                    40038
#define IDM_CLEARBM                     40039
#define IDM_FIRSTBM                     40040
#define IDM_NEXTBM                      40041
#define IDM_PREVBM                      40042
#define IDM_LASTBM                      40043
#define IDM_MATCH                       40044
#define IDM_CASCADE                     40045
#define IDM_TILEHORZ                    40046
#define IDM_TILEVERT                    40047
#define IDM_ARRANGE                     40048
#define IDM_PAGESETUP                   40050
#define IDM_PASTENEW                    40051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         40052
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
