//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BCC.rc
//
#define IDS_APP_TITLE                   1
#define IDS_CPL_INFO                    2
#define IDS_CPL_NAME                    3
#define IDS_SETTINGS_LOCATION           4
#define IDS_NO_BRAINCHILD               5
#define IDS_NO_MEMORY                   6
#define IDS_NO_SETTINGS                 7
#define IDS_TOOL_NEW                    8
#define IDS_TOOL_DELETE                 9
#define IDS_TOOL_UP                     10
#define IDS_TOOL_DOWN                   11
#define IDS_ABOUT                       12
#define IDS_COPYRIGHT                   13
#define IDS_DISCLAIMER                  14
#define IDS_NO_PAGE                     15
#define IDS_NO_ITEM                     16
#define IDS_PAGE_PRINTER                17
#define IDS_COMMENT_PRINT               18
#define IDS_NORMAL                      19
#define IDS_WIDE                        20
#define IDS_BLOCK                       21
#define IDS_DEFAULT_TITLE               22
#define IDS_HOPS_RANGE                  23
#define IDS_COMMENT_GENERAL             24
#define IDS_PAGE_DATETIME               25
#define IDS_COMMENT_DATETIME            26
#define IDS_PAGE_FILES                  27
#define IDS_DOS                         28
#define IDS_UNIX                        29
#define IDS_MAC                         30
#define IDS_COMMENT_FILES               31
#define IDS_PAGE_SYNTAX                 32
#define IDS_TEXT                        33
#define IDS_BACKGROUND                  34
#define IDS_BACKGROUND_READONLY         35
#define IDS_MARGIN                      36
#define IDS_BOOKMARK                    37
#define IDS_NUMBER                      38
#define IDS_DELIMITER                   39
#define IDS_SELTEXT                     40
#define IDS_SELTEXTBKGND                41
#define IDS_BLOCK_NONAME                42
#define IDS_NEW_BLOCK                   43
#define IDS_DEFAULT                     44
#define IDS_CUSTOM                      45
#define IDS_ERROR_EMPTYSTRING           46
#define IDS_HIST_RANGE                  46
#define IDS_SURE                        47
#define IDS_YESNO                       48
#define IDS_ERROR_NAME                  49
#define IDS_ERROR_SAMENAME              50
#define IDS_NEWCLASS                    51
#define IDS_TOOL_EDIT                   52
#define IDS_TOOL_INSERT                 53
#define IDS_TOOL_COLOR                  54
#define IDS_COLOR_FMT                   55
#define IDS_KEYWORD_DELETE              56
#define IDS_INSERT_KEYWORDS             57
#define IDS_ERROR_SAVETEMP              58
#define IDS_COMMENT_COLORS              59
#define IDS_COMMENT_SYNTAXGENERAL       60
#define IDS_COMMENT_BLOCKS              61
#define IDS_COMMENT_KEYWORDS            62
#define IDS_NO_BACKUP                   63
#define IDS_ERROR_FILE                  64
#define IDS_PAGE_INDENT                 65
#define IDS_COMMENT_INDENTION           66
#define IDS_ERROR_NOEMPTY               67
#define IDS_NEWSMART_ENTRY              68
#define IDS_PAGE_KEYBOARD               69
#define IDS_HARDCODED                   70
#define IDS_INSERT                      71
#define IDS_RUN                         72
#define IDS_OPEN                        73
#define IDS_ERROR_BACKUPPATH            74
#define IDS_NEWINSERT                   75
#define IDS_RUN_TITLE                   76
#define IDS_SHELLOPEN_TITLE             77
#define IDS_EXEC_FILTER                 78
#define IDS_ALL_FILTER                  79
#define IDS_COMMENT_KEYS                80
#define IDS_ERROR_TABSIZE               81
#define IDS_LINENUMBER                  82
#define IDS_LINENUMBERBKGND             83
#define IDS_STRING84                    84
#define IDS_HORIZONTAL                  84
#define IDS_ERROR_COLUMNMARKER          85
#define IDS_BACKGROUND_NUMBER           86
#define IDS_BACKGROUND_DELIM            87
#define IDS_TOOL_BGCOLOR                88
#define IDS_TRANSPARENT                 89
#define IDS_BRACKET_MATCH               90
#define IDS_AUTOMATCH                   91
#define IDS_VISIBLE_ERROR               92
#define IDS_CLEAR_SPACES                93
#define IDS_ENABLE_DND                  94
#define IDS_SHOW_MARGIN                 95
#define IDS_SOLID_MARGIN                96
#define IDS_LINE_NUMBERS                97
#define IDS_FAST_SCROLL                 98
#define IDS_CLEAR_UNDO                  99
#define IDS_VISIBLE_SPACE               100
#define IDD_MAIN                        101
#define IDS_CASE_FIXING                 101
#define IDD_ABOUT                       102
#define IDS_COLOR_MATCH                 102
#define IDI_ABOUT                       103
#define IDS_LINE_HIGHLIGHT              103
#define IDI_PRINTER                     104
#define IDS_HIGHLIGHT_LINE              104
#define IDD_PRINTING                    105
#define IDS_REALLY_EXIT                 105
#define IDD_GENERAL                     106
#define IDS_YESAPPLYNO                  106
#define IDI_GENERAL                     107
#define IDD_DATETIME                    107
#define IDS_PARSEHYPERLINKS             107
#define IDD_FILES                       108
#define IDI_FILES                       108
#define IDS_HYPERLINK                   108
#define IDD_SYNTAX                      109
#define IDS_HYPERLINK_BKGND             109
#define IDD_BLOCK                       110
#define IDS_SHOWHYPERTIPS               110
#define IDD_KEYWORDS                    113
#define IDD_KWEDIT                      115
#define IDD_APPLY                       116
#define IDB_CLIST                       117
#define IDR_POPUP                       119
#define IDD_KEYRECORD                   120
#define IDD_HARDCODED                   121
#define IDD_INSERTEDIT                  122
#define IDD_RUN                         123
#define IDB_TREE                        125
#define IDB_MAIN                        126
#define IDD_CLASSNAME                   130
#define IDD_INDENT                      131
#define IDD_KEYBOARD                    132
#define IDC_TREE                        1000
#define IDI_MAIN                        1001
#define IDC_OK                          1001
#define IDI_WWW                         1002
#define IDC_CANCEL                      1002
#define IDC_PRINT_HEADER                1002
#define IDI_EMAIL                       1003
#define IDC_APPLY                       1003
#define IDC_HLEFT                       1003
#define IDC_PAGEBAR                     1004
#define IDB_TOOLS                       1004
#define IDI_INDENTION                   1004
#define IDC_HMID                        1004
#define IDC_HRIGHT                      1005
#define IDI_DATETIME                    1005
#define IDC_PRINT_FOOTER                1006
#define IDI_SYNTAX                      1006
#define IDC_MORE                        1007
#define IDC_FLEFT                       1007
#define IDI_KEYBOARD                    1007
#define IDC_COPYRIGHT                   1008
#define IDC_FMID                        1008
#define IDC_DISCLAIMER                  1009
#define IDC_FRIGHT                      1009
#define IDC_COLORS                      1010
#define IDC_HTTP                        1011
#define IDC_SCREEN                      1011
#define IDC_EMAIL                       1012
#define IDC_SELECT                      1012
#define IDC_FONT                        1013
#define IDC_LINENUMS                    1014
#define IDC_TOOLS                       1016
#define IDC_CLASS                       1016
#define IDC_EXT                         1017
#define IDC_KEYS                        1017
#define IDC_DELIM                       1018
#define IDC_COMTOOLS                    1018
#define IDC_CARET                       1019
#define IDC_AUTOMATCH                   1020
#define IDC_COMMANDS                    1020
#define IDC_VISIBLE                     1021
#define IDC_CLEAR                       1022
#define IDC_ENABLEDND                   1023
#define IDC_SHOWSEL                     1024
#define IDC_FAST                        1025
#define IDC_SYNTAX                      1026
#define IDC_HOPS                        1027
#define IDC_UDHOPS                      1028
#define IDC_ST_HEAD                     1029
#define IDC_HIST                        1029
#define IDC_ST_FOOT                     1030
#define IDC_UDHIST                      1030
#define IDC_ST_OPT                      1031
#define IDC_ST_GEN                      1032
#define IDC_ST_GLOB                     1033
#define IDC_ST_DTF                      1034
#define IDC_COLMARKER_OFFSET            1034
#define IDC_DATE                        1035
#define IDC_UD_OFFSET                   1035
#define IDC_TIME                        1036
#define IDC_ST_DTS                      1037
#define IDC_DATE_SAMP                   1038
#define IDC_TIME_SAMP                   1039
#define IDC_RECORD_EDIT                 1039
#define IDC_ST_DEF                      1040
#define IDC_RECORD_OK                   1040
#define IDC_DEFAULTMODE                 1041
#define IDC_RECORD_CANCEL               1041
#define IDC_ST_BACK                     1042
#define IDC_BACKUP                      1043
#define IDC_ST_AS                       1044
#define IDC_BAK                         1045
#define IDC_BAKEXT                      1046
#define IDC_EXTBAK                      1047
#define IDC_EXTIN                       1048
#define IDC_FOLDER                      1049
#define IDC_BLOCKS                      1050
#define IDC_COMMON                      1051
#define IDC_ESCAPE                      1054
#define IDC_KEYWORDS                    1056
#define IDC_COLOR                       1057
#define IDC_BGCOLOR                     1058
#define IDC_COMMAND                     1061
#define IDC_LIST                        1062
#define IDC_ARGS                        1062
#define IDC_WORDS                       1063
#define IDC_CASE                        1066
#define IDC_EDIT                        1068
#define IDC_AUTO                        1069
#define IDC_SMART                       1070
#define IDC_START                       1071
#define IDC_EOL                         1072
#define IDC_LEFT                        1072
#define IDC_WHITE                       1073
#define IDC_RIGHT                       1073
#define IDC_CHARS                       1074
#define IDC_TABSIZE                     1074
#define IDC_END                         1075
#define IDC_TABSIZE_SPIN                1075
#define IDC_NAME                        1077
#define IDC_RUN                         1078
#define IDC_CLEARUNDO                   1079
#define IDC_VISIBLESPACE                1080
#define IDC_INSERT                      1081
#define IDC_TITLE                       1082
#define IDC_TREE1                       1087
#define IDC_OPTIONS                     1087
#define IDC_COLMARKER                   1088
#define IDC_SEP                         1091
#define IDC_LABEL1                      1092
#define IDC_LABEL2                      1093
#define IDC_SOL                         1148
#define IDC_STATIC_ARGS                 1156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
