//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BCDemo.rc
//
#define IDB_SMALL_SIDEBAR               9
#define IDB_TOOLBAR                     101
#define IDD_FIF                         101
#define IDI_ICON                        103
#define IDR_CHILDMENU                   106
#define IDR_ACCEL                       107
#define IDM_XPSYLEMENUS                 108
#define ID_OPTIONS_XPSTYLEMENUS         109
#define IDM_WINDOWS                     110
#define ID_WINDOW_WINDOWS               111
#define IDM_ABOUTBRAINCHILD             112
#define ID_Menu                         114
#define ID_DUMMY_IDM                    115
#define ID_CHANGECASING_A               120
#define ID_CHANGECASING_B               121
#define ID_CHANGECASING_C               122
#define ID_CHANGECASING_D               123
#define ID_CHANGECASING_E               124
#define ID_CHANGECASING_F               125
#define ID_CHANGECASING_G               126
#define ID_CHANGECASING_H               127
#define ID_CHANGECASING_I               128
#define ID_CHANGECASING_J               129
#define ID_CHANGECASING_K               130
#define ID_CHANGECASING_L               131
#define ID_CHANGECASING_M               132
#define ID_CHANGECASING_N               133
#define ID_CHANGECASING_O               134
#define ID_CHANGECASING_P               135
#define ID_CHANGECASING_Q               136
#define ID_CHANGECASING_R               137
#define ID_CHANGECASING_S               138
#define ID_CHANGECASING_T               139
#define ID_CHANGECASING_U               140
#define ID_CHANGECASING_V               141
#define ID_CHANGECASING_W               142
#define ID_CHANGECASING_X               143
#define ID_CHANGECASING_Y               144
#define ID_CHANGECASING_Z               145
#define ID_CHANGECASING_0               146
#define ID_CHANGECASING_1               147
#define ID_CHANGECASING_2               148
#define ID_CHANGECASING_3               149
#define ID_CHANGECASING_4               150
#define ID_CHANGECASING_5               151
#define ID_CHANGECASING_6               152
#define ID_CHANGECASING_7               153
#define ID_CHANGECASING_8               154
#define ID_CHANGECASING_9               155
#define ID_CHANGECASING_A156            156
#define ID_CHANGECASING_B157            157
#define ID_CHANGECASING_C158            158
#define ID_CHANGECASING_D159            159
#define ID_CHANGECASING_E160            160
#define ID_CHANGECASING_F161            161
#define ID_CHANGECASING_G162            162
#define ID_CHANGECASING_H163            163
#define ID_CHANGECASING_I164            164
#define ID_CHANGECASING_J165            165
#define ID_CHANGECASING_K166            166
#define ID_CHANGECASING_L167            167
#define ID_CHANGECASING_M168            168
#define ID_CHANGECASING_N169            169
#define ID_CHANGECASING_O170            170
#define ID_CHANGECASING_P171            171
#define ID_CHANGECASING_Q172            172
#define ID_CHANGECASING_R173            173
#define ID_CHANGECASING_S174            174
#define ID_CHANGECASING_T175            175
#define ID_CHANGECASING_U176            176
#define ID_CHANGECASING_V177            177
#define ID_CHANGECASING_W178            178
#define ID_CHANGECASING_X179            179
#define ID_CHANGECASING_Y180            180
#define ID_CHANGECASING_Z181            181
#define IDR_BRAINCHILD_DLL              187
#define IDR_LOGFILE_BCB                 190
#define IDR_ENTEO_LOG_FILE_BCB          190
#define IDI_LOGFILE_ICON                192
#define IDD_LOG_FOLDER                  200
#define IDR_DOWNLOAD_AVI                206
#define IDR_MAPIMAIL_EXE                208
#define IDR_RT_FILE1                    209
#define IDC_FIND                        1000
#define IDC_FOLDER                      1002
#define IDC_LIST1                       1003
#define IDC_LOGFILE_LIST                1003
#define IDC_EDIT1                       1004
#define IDC_LIST                        1004
#define IDC_FILTER_BOX                  1004
#define IDC_COMBO1                      1005
#define IDC_CASE                        1005
#define IDC_FOLDER_COMBO                1005
#define IDC_GO                          1006
#define IDC_CHECK1                      1007
#define IDC_RECUR                       1007
#define IDC_OCC                         1008
#define IDC_PATH_RADIO                  1012
#define IDC_COMPUTER_RADIO              1013
#define IDC_PROC                        1014
#define IDC_STATIC_1                    1015
#define IDC_CHANGE_FOLDER_BUTTON        1015
#define IDC_STATIC_2                    1016
#define IDC_FILTER_BUTTON               1016
#define IDC_STATIC_3                    1017
#define IDC_LOGFOLDER_LINK              1017
#define IDC_STATIC_4                    1018
#define IDC_STATIC_5                    1019
#define IDD_SIDEBAR                     1022
#define IDC_SIDEBAR_HEADER              1022
#define IDC_FOLDER_HEADER               1024
#define IDR_MANIFEST                    1024
#define IDC_FILTER_TEXT                 1025
#define IDC_ANIMATE                     1027
#define IDC_RADIO1                      1028
#define IDC_LOCAL_RADIO                 1028
#define IDC_COMPUTER_COMBO              1029
#define IDM_OPEN                        40002
#define IDM_EXIT                        40005
#define IDM_PASTENEW                    40006
#define IDM_NEWONSTART                  40009
#define IDM_FANCYMENU                   40010
#define IDM_ABOUT                       40011
#define IDM_CLOSE                       40012
#define IDM_CLOSEALL                    40013
#define IDM_SAVE                        40014
#define IDM_SAVEAS                      40016
#define IDM_SAVEALL                     40017
#define IDM_PROPERTIES                  40019
#define IDM_PRINT                       40020
#define IDM_RECENTFILES                 40021
#define IDM_UNDO                        40023
#define IDM_REDO                        40024
#define IDM_CUT                         40025
#define IDM_COPY                        40026
#define IDM_PASTE                       40027
#define IDM_DELETE                      40028
#define IDM_SELECTALL                   40029
#define IDM_INVERTCASE                  40030
#define IDM_UPPERCASE                   40031
#define IDM_LOWERCASE                   40032
#define IDM_FIND                        40033
#define IDM_FINDNEXT                    40034
#define IDM_FINDPREV                    40035
#define IDM_REPLACE                     40036
#define IDM_GOTO                        40037
#define IDM_TOGGLEBM                    40038
#define IDM_CLEARBM                     40039
#define IDM_FIRSTBM                     40040
#define IDM_NEXTBM                      40041
#define IDM_PREVBM                      40042
#define IDM_LASTBM                      40043
#define IDM_MATCH                       40044
#define IDM_CASCADE                     40045
#define IDM_TILEVERT                    40047
#define IDM_ARRANGE                     40048
#define IDM_NEW                         40050
#define IDM_HOTFILES                    40051
#define IDM_READONLY                    40053
#define IDM_ADDTOHOT                    40054
#define IDM_NEWWINDOW                   40055
#define IDB_FOLDERCHANGE                40056
#define IDM_NEXTWND                     40061
#define IDM_PREVWND                     40062
#define IDM_OVERVIEW                    40071
#define IDM_RELOAD_FILE                 40075
#define IDM_TILEHORZ                    40078
#define IDM_SHOWSIDEBAR                 40082
#define IDM_CHANGELOGFOLDER             40088
#define IDM_AUTOMATICALLYSHOWSIDEBAR    40089
#define IDM_REGISTERFILEEXTENSION       40090
#define IDM_FINDINFILES                 40092
#define IDM_OPEN_SELECTED_PATH          40099
#define IDM_OPEN_FOLDER                 40100
#define IDM_CHANGE_LOGFOLDER            40102
#define IDM_PAGESETUP                   40103
#define IDM_COMMANDLINEPARAMETERS       40108
#define IDM_MINIMIZE_SIDEBAR            40110
#define ID_LOGFOLDER_DELETEFILES        40113
#define ID_DELETEFILES_OLDERTHAN1MINUTE 40115
#define ID_DELETEFILES_OLDERTHAN1HOUR   40116
#define ID_DELETEFILES_OLDERTHAN1DAY    40117
#define IDM_DELETE_ALL_FILES            40123
#define ID_DELETEFILES_OLDERTHAN1WEEK   40127
#define ID_DELETEFILES_OLDERTHAN1MONTH  40128
#define ID_DELETE_OLDER_THAN_ONE_MINUTE 40129
#define IDM_DELETE_OLDER_ONE_MINUTE     40130
#define IDM_DELETE_OLDER_ONE_HOUR       40131
#define IDM_DELETE_OLDER_ONE_DAY        40132
#define IDM_DELETE_OLDER_ONE_WEEK       40133
#define IDM_DELETE_OLDER_ONE_MONTH      40134
#define IDM_SCROLL_TO_END_ON_FILE_LOAD  40135
#define ID_FILE_SENDASEMAIL             40136
#define IDM_SEND_AS_EMAIL               40137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         40138
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
